# Generated by Django 5.2.7 on 2025-10-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrochamada',
            name='revista',
            field=models.BooleanField(default=False, verbose_name='Revista'),
        ),
    ]
