# Generated by Django 5.2.7 on 2025-10-25 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aluno_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_totais', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroChamadaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca', models.BooleanField(default=False, verbose_name='Presença')),
                ('biblia', models.BooleanField(default=False, verbose_name='Bíblia')),
                ('revista', models.BooleanField(default=False, verbose_name='Revista')),
                ('oferta', models.BooleanField(default=False, verbose_name='Oferta')),
                ('convidado', models.BooleanField(default=False, verbose_name='Convidado')),
                ('pontos_ganhos', models.IntegerField(default=0)),
                ('chamada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_professor', to='core.chamada')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_de_chamada', to='core.perfilprofessor')),
            ],
        ),
    ]
