# Generated by Django 5.2.7 on 2025-10-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilprofessor_registrochamadaprofessor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilprofessor',
            options={'verbose_name': 'Perfil de Professor', 'verbose_name_plural': 'Perfis de Professor'},
        ),
    ]
