# Generated by Django 5.2.7 on 2025-10-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_perfilprofessor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrochamada',
            name='atividades',
            field=models.BooleanField(default=False, verbose_name='Questionário'),
        ),
        migrations.AlterField(
            model_name='registrochamada',
            name='versiculo',
            field=models.BooleanField(default=False, verbose_name='Texto Bíblico'),
        ),
    ]
