# Generated by Django 5.2.7 on 2025-11-03 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_registrochamada_atividades_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
        migrations.AddField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Professores'}, related_name='turmas_lecionadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
