# Generated by Django 5.2.7 on 2025-11-03 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_turma_professor_turma_professores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrochamadaprofessor',
            name='chamada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_de_professor', to='core.chamada'),
        ),
        migrations.AlterUniqueTogether(
            name='registrochamadaprofessor',
            unique_together={('chamada', 'professor')},
        ),
    ]
